=== padcom/rtmgr/source/components/pxlib/CLPMaker/clpmaker.dtd
<!ELEMENT options     (unit, class, option+) >
<!ELEMENT unit        (#PCDATA) >
<!ELEMENT class       (#PCDATA) >
<!ELEMENT option      (name, short, long, explanation) >
<!ELEMENT name        (#PCDATA) >
<!ELEMENT short       (#PCDATA) >
<!ELEMENT long        (#PCDATA) >
<!ELEMENT explanation (#PCDATA) >
<!ATTLIST option      
  type (bool | string) #REQUIRED>

=== padcom/rtmgr/source/components/pxlib/CLPMaker/example.xml
<?xml version="1.0"?>

<!DOCTYPE options SYSTEM "clpmaker.dtd">

<options>
  <unit>Example</unit>
  <class>TOptions</class>
  
  <option type="bool">
    <name>Help</name>
    <short>h</short>
    <long>help</long>
    <explanation>Show help</explanation>
  </option>
  
  <option type="string">
    <name>InputFile</name>
    <short>i</short>
    <long>input-file</long>
    <explanation>Input file name</explanation>
  </option>
</options>
